config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :categories, except: %i[edit update] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :recipe
  belongs_to :category
  validates :recipe, uniqueness: { scope: :category }
  validates :comment, length: { minimum: 6 }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :recipes, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :bookmarks
  has_many :categories, through: :bookmarks
  validates :name, :description, presence: true
  validates :name, uniqueness: true
  validates :rating, numericality: { greater_than_or_equal_to: 0.0, less_than_or_equal_to: 10.0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @bookmark = Bookmark.new
  end

  def create
    @category = Category.find(params[:category_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.category = @category
    if @bookmark.save
      redirect_to category_path(@category)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to category_path(@bookmark.category)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :recipe_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to category_path(@category)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to :categories_path, status: :see_other
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/bookmarks/new.html.erb
<h1>Add a new bookmark to <%= @category.name.capitalize %></h1>

<%= simple_form_for [@category, @bookmark] do |f| %>
  <%= f.association :recipe %>
  <%= f.input :comment %>
  <%= f.submit %>
<% end %>

<%= link_to "back", category_path(@category) %>

app/views/categories/index.html.erb
<h1>View your Cookbook categories here</h1>
<ul>
  <% @categories.each do |category| %>
    <li>
      <h2><%= link_to category.name.capitalize, category_path(category) %> | <%= link_to "delete", category_path(category), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></h2>
    </li>
  <% end %>
</ul>

app/views/categories/new.html.erb
<h1>Add a new category to your cookbook</h1>


<%= simple_form_for(@category) do |f| %>
  <%= f.input :name %>
  <%= f.submit "add category" %>
<% end %>

<%= link_to "back to all categories", categories_path %>

app/views/categories/show.html.erb
<h1><%= @category.name.capitalize %></h1>
<ul>
  <% @category.bookmarks.each do |bookmark| %>
    <li style="list-style:none;">
      <div style="display:flex;align-items:center;">
      <h2 style="padding-right:8px;"><%= bookmark.recipe.name %> |</h2>
      <%= link_to "delete", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
      </div>
      <p><em>"<%= bookmark.recipe.description %>"</em></p>
      <p>rating: <%= bookmark.recipe.rating %></p>
    </li>
  <% end %>
  <%= link_to "add a recipe", new_category_bookmark_path(@category) %>
</ul>
<p><%= link_to "back to all categories", categories_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCookbookComplete</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>